# Generated by Django 4.2.2 on 2023-07-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='parknum',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
