# Generated by Django 4.2.2 on 2023-07-01 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_territory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('placetype', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='main_app.state')),
            ],
        ),
    ]
