# Generated by Django 4.2.2 on 2023-07-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_placeterritory'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='image',
            field=models.CharField(default='-', max_length=500),
        ),
        migrations.AddField(
            model_name='placeterritory',
            name='image',
            field=models.CharField(default='-', max_length=500),
        ),
    ]
