# Generated by Django 4.2.2 on 2023-07-05 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_remove_featured_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='featured',
            name='name',
            field=models.CharField(default='Homepage', max_length=100),
        ),
    ]
